# wrangler.toml
name = 'edgetn'

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"
no_bundle = true

compatibility_date = "2024-11-27"

[vars]
UUID = "0b25fbd8-9ef2-4c42-9b78-023738b829ed"
