# wrangler.toml
name = 'edgetn-vless'

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"
no_bundle = true

compatibility_date = "2024-11-27"

[vars]
UUID = "c8272f42-f670-4a03-b9fd-23b75c43ed05"
